### ISSUE TITLE
panic: runtime error: index out of range [0] with length 0 in ADO

### ISSUE THREAD

**Issue by jadamsHCBB** [armosec/kubescape#333]
I am getting the below output when attempting to run the kubescape scan command. This step is inside of a template from a repo
that ran fine before I added the script to a template. The script is below:

```
kubescape scan framework nsa $(Build.Repository.LocalPath)/k8s/kustomize/overlays/dev/*.yaml --format junit --output Results/results.xml --verbose
```

It then spits this out: 

```
The working directory is /home/vsts/work/1/s
ARMO security scanner starting
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[progress] Scanning cluster 
[success] Done scanning cluster 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/armosec/kubescape/resultshandling/printer/v1.convertPostureReportToJunitResult(0xc0007da000)
	/home/runner/work/kubescape/kubescape/resultshandling/printer/v1/junit.go:110 +0x67c
github.com/armosec/kubescape/resultshandling/printer/v1.(*JunitPrinter).ActionPrint(0xc00011a108, 0xc0000801e0)
	/home/runner/work/kubescape/kubescape/resultshandling/printer/v1/junit.go:32 +0x3e
github.com/armosec/kubescape/resultshandling.(*ResultsHandler).HandleResults(0xc00010fc28, 0xc0008ca498)
	/home/runner/work/kubescape/kubescape/resultshandling/results.go:30 +0x58
github.com/armosec/kubescape/clihandler.ScanCliSetup(0x3183f20)
	/home/runner/work/kubescape/kubescape/clihandler/initcli.go:143 +0x639
github.com/armosec/kubescape/clihandler/cmd.glob..func12(0x3164dc0, {0xc00020a140, 0x5, 0xa})
	/home/runner/work/kubescape/kubescape/clihandler/cmd/framework.go:100 +0x395
github.com/spf13/cobra.(*Command).execute(0x3164dc0, {0xc0000a9d60, 0xa, 0xa})
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x3166940)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/armosec/kubescape/clihandler/cmd.Execute(...)
	/home/runner/work/kubescape/kubescape/clihandler/cmd/root.go:30
main.main()
	/home/runner/work/kubescape/kubescape/main.go:8 +0x25
##[error]Bash exited with code '2'.
Finishing: Kubescape Scan
```
Not really sure what is happening. Any help would be appreciated.

**Comment by qgervacio** [comment]
Encountered same too.

```
❯ ls -lrt 
total 105464
-rwxr-xr-x@ 1 abc123  staff  52937312 Jan 20 02:26 kubescape-macos-latest
-rw-r--r--  1 abc123  staff    205474 Jan 20 10:49 mitre.json
-rw-r--r--  1 abc123  staff    124440 Jan 20 10:49 nsa.json
-rw-r--r--  1 abc123  staff       296 Jan 20 10:49 test.yaml

❯ ./kubescape-macos-latest version
Your current version is: v2.0.141

❯ cat test.yaml 
apiVersion: v1
kind: ServiceAccount
metadata:
  name: auditsvc
  labels:
    helm.sh/chart: auditsvc-1.0.0
    app.kubernetes.io/name: auditsvc
    app.kubernetes.io/instance: RELEASE-NAME
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: idaas
    app.kubernetes.io/env: dev

❯ ./kubescape-macos-latest scan framework nsa test.yaml --use-from nsa.json --format junit --output junit.xml
ARMO security scanner starting
Warning: failed to get config inputs from github release, this may affect the scanning results
[progress] Downloading/Loading policy definitions
[success] Downloaded/Loaded policy
[progress] Scanning cluster 
[success] Done scanning cluster 
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/armosec/kubescape/resultshandling/printer/v1.convertPostureReportToJunitResult(0xc000562000)
        /Users/runner/work/kubescape/kubescape/resultshandling/printer/v1/junit.go:110 +0x67c
github.com/armosec/kubescape/resultshandling/printer/v1.(*JunitPrinter).ActionPrint(0xc0003b0010, 0xc000064720)
        /Users/runner/work/kubescape/kubescape/resultshandling/printer/v1/junit.go:32 +0x3e
github.com/armosec/kubescape/resultshandling.(*ResultsHandler).HandleResults(0xc000a9fc28, 0xc000283350)
        /Users/runner/work/kubescape/kubescape/resultshandling/results.go:30 +0x58
github.com/armosec/kubescape/clihandler.ScanCliSetup(0x3d87ba0)
        /Users/runner/work/kubescape/kubescape/clihandler/initcli.go:143 +0x639
github.com/armosec/kubescape/clihandler/cmd.glob..func12(0x3d68f00, {0xc0001a1100, 0x2, 0x8})
        /Users/runner/work/kubescape/kubescape/clihandler/cmd/framework.go:100 +0x395
github.com/spf13/cobra.(*Command).execute(0x3d68f00, {0xc0001a1080, 0x8, 0x8})
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x3d6aa80)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/armosec/kubescape/clihandler/cmd.Execute(...)
        /Users/runner/work/kubescape/kubescape/clihandler/cmd/root.go:30
main.main()
        /Users/runner/work/kubescape/kubescape/main.go:8 +0x25
❯ 
```

**Comment by slashben** [comment]
thanks guys sending this issue, we are looking into it

**Comment by wim-de-groot** [comment]
Right now it is assumed that the a `[rule report](https://github.com/armosec/kubescape/blob/c00bc0ebbb354d454db0fe8beb8fab7f0768499a/resultshandling/printer/v1/junit.go#L110)` at  index 0 is away present, but that is not the case.

My solution to this problem would be to extend the [if](https://github.com/armosec/kubescape/blob/c00bc0ebbb354d454db0fe8beb8fab7f0768499a/resultshandling/printer/v1/junit.go#L110) statement with a check if the length of the `controlReports.RuleReports` is greater than zero.

Is it okay if I open a pull request for this solution?

**Comment by slashben** [comment]
Sure, open a PR against our "dev" branch and @dwertent  will review, thx!
