### ISSUE TITLE
Kubescape scan on rbac fail

### ISSUE THREAD

**Issue by mcolladoio** [armosec/kubescape#336]
With the latest version of kubescape (2.0.141), I am getting the below error on my scans on the kubernetes cluster. 

```
kubescape submit rbac --account <account id>
W0120 18:13:43.576691   45584 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
W0120 18:13:44.095746   45584 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x256c7bc]

goroutine 1 [running]:
github.com/armosec/kubescape/cautils.ReportV2ToV1(0x0)
	/Users/runner/work/kubescape/kubescape/cautils/reportv2tov1.go:16 +0x3c
github.com/armosec/kubescape/resultshandling/reporter/v1.(*ReportEventReceiver).ActionSendReport(0xc0009b20c0, 0xc000395260)
	/Users/runner/work/kubescape/kubescape/resultshandling/reporter/v1/reporteventreceiver.go:41 +0x2a
github.com/armosec/kubescape/clihandler.Submit({{0x2dac3b8, 0xc00000e0a0}, {0x2dc7640, 0xc0009b20c0}, {0x2de21b8, 0xc000112ec0}})
	/Users/runner/work/kubescape/kubescape/clihandler/initcli.go:185 +0xd4
github.com/armosec/kubescape/clihandler/cmd.glob..func20(0x3d69180, {0x2a21021, 0x2, 0x2})
	/Users/runner/work/kubescape/kubescape/clihandler/cmd/rbac.go:43 +0x2ce
github.com/spf13/cobra.(*Command).execute(0x3d69180, {0xc00081e8c0, 0x2, 0x2})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0x3d6aa80)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/armosec/kubescape/clihandler/cmd.Execute(...)
	/Users/runner/work/kubescape/kubescape/clihandler/cmd/root.go:30
main.main()
	/Users/runner/work/kubescape/kubescape/main.go:8 +0x25
```
CLI Version: 2.0.141
MacOS Monterry 12.1 - M1

Ref: #149

**Comment by rotemamsa** [comment]
hi there!
we just released a hotfix version with a fix for RBAC usage. please check it out and replay if all as expected.

BR,
Rotem

**Comment by mcolladoio** [comment]
hi there!
Everything is working fine! 
Thanks
